### PR TITLE
close #2 -- remove unnecessary import "C"

### LINKED ISSUE #2: why import "C" is required
Hi Vladimir, 

Thanks for the excellent example of  Go 1.8's plugin. One question, why import "C" is required? 

That `import "C"` doesn't show up in https://tip.golang.org/pkg/plugin/, nor your https://medium.com/learning-the-go-programming-language/writing-modular-go-programs-with-plugins-ec46381ee1a9 or https://github.com/vladimirvivien/go-plugin-example, but in the source code it say, 

> // required

why? thanks!

### PR DESCRIPTION
**Pull request by suntong**
It is in fact not necessary. Tested.

### CODE REVIEW

**Comment by vladimirvivien** [comment]
@suntong thanks for the contrib!

**Comment by suntong** [comment]
thanks for taking it.

**Comment by suntong** [comment]
Hold on, you closed it without taking it?

**Comment by suntong** [comment]
> If you find that it's not needed, please submit a PR and I will approve. Thanks again!

<sigh>, if you're not planning to take it, why bother saying above (in https://github.com/vladimirvivien/go-plugin-example/issues/2)? Why wasting others time and trust like this? 

<shake my head...> :-1:

**Comment by vladimirvivien** [comment]
@suntong it was my bad and apologies. I closed it without actually merging by mistake.  I just did... 

In the future though, this
> Why wasting others time and trust like this? 

Not necessary. You could have simply asked what happened, and I would have gladly tell you.  

I do this on my spare time just as, I am sure, you are as well and I appreciate it.  Keep in mind this is, as you pointed out, based on trust and I find the remark lacking trust in the community, project, and people from your part.

**Comment by suntong** [comment]
I did asked, "_Hold on, you closed it without taking it?_", and waited for more than 20 days, but didn't get any reply. 

Thanks for taking the PR.

**Pull request merged**
